name: 'depcruise'
on:
  pull_request:

jobs:
  report:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: 依存関係確認
        uses: MH4GF/dependency-cruiser-report-action@v2.5
        with:        
          package_manager: 'npm'
          working-directory: app
